### Get all albums
GET http://localhost:8080/api/albums
Accept: application/json

### Get an album with the given id
GET http://localhost:8080/api/albums/1

### Delete an album with the given id
DELETE localhost:8080/api/albums/1


### Post a new album resource
POST http://localhost:8080/api/albums
Content-Type: application/json

{"artist":"KISS", "albumTitle":"Destroyer", "recordLabel":"Party On Records", "albumArt":"https://images-na.ssl-images-amazon.com/images/I/71pceb8qNFL._SX522_.jpg"}

### Update an album resource
PATCH http://localhost:8080/api/albums/1/albumTitle

FlavorTown

### Update an album's song list
POST http://localhost:8080/api/albums/34/songs
Content-Type: application/json

{"album":"Destroyer", "songTitle":"Detroit Rock City", "duration":"2:47", "songLink":"www.youtube.com"}


### Add a new album resource
POST http://localhost:8080//api/albums/1/comments
Content-Type: application/json

{"author": "Art", "headline": "FOREIGNERS!", "comment": "Ummmm, No Comment."}


### View all comments associated with album ID
GET http://localhost:8080//api/albums/5/comments
Accept: application/json



