### Get all albums
GET http://localhost:8080/api/albums
Accept: application/json

### Get an album with the given id
GET http://localhost:8080/api/albums/1

### Delete a campus with the given id


### Post a new album resource


### Update an album resource


### Update an album's


### Add a new album resource


