
### Get all songs with given Album id
GET http://localhost:8080/api/albums/1

### Get a song with a given id
GET http://localhost:8080/api/songs/13

### Delete a song with the given id
DELETE localhost:8080/api/songs/9


### Post a new song resource
POST http://localhost:8080/api/albums
Content-Type: application/json

{"artist":"KISS", "albumTitle":"Destroyer", "recordLabel":"Party On Records", "albumArt":"https://images-na.ssl-images-amazon.com/images/I/71pceb8qNFL._SX522_.jpg"}

### Update a song resource
PATCH http://localhost:8080/api/songs/12/songTitle

Pajama Time

### Update an song
POST http://localhost:8080/api/albums/34/songs
Content-Type: application/json

{"album":"Destroyer", "songTitle":"Detroit Rock City", "duration":"2:47", "songLink":"www.youtube.com"}


### Add a new song resource
POST http://localhost:8080//api/songs/13/comments
Content-Type: application/json

{"author": "Art", "headline": "URGENT", "comment": "No Comment"}

### View individual comment associated with song ID
GET http://localhost:8080//api/song/13/comments
Accept: application/json



